### ISSUE TITLE
Large Artifacts Caches to /tmp First Before Writing to Destination

### ISSUE THREAD

**Issue by kahoffman** [autostructure/artifactory_utils#1]
I've encountered a problem where very large artifact will cache to /tmp before writing to the final destination. In most cases /tmp is not big enough to hold the cached response. In my case I am talking about 8G artifacts. There does seem to be a way in the Net::HTTP ruby module to stream a response body directly to a destination though this module does not currently use this feature. Some consideration should be given to a parameter that allows the specification of a destination tmp path or default to the destination if given. The caveat would be you need double the space to transfer the file down.

**Comment by kahoffman** [comment]
The issue appears to be that open_uri uses a temp file to cache the response body. I would recommend something like the below for the write_file function in artifact_sync/linux.rb to utilize streaming direct to disk. The below is working at our site.

``` ruby
  # Write a new file to the destination
  def write_file(url, destination, user_name, password_hash)

    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Get.new(uri.request_uri)

    # user and password_hash are here use auth
    if user_name and password_hash
      request.basic_auth user_name, password_hash
    end

    http.request(request) do |response|
      if response.code != "200"
        raise Puppet::Error, 'No file can be found at ' + url
      else
        open destination, 'w' do |io|
          response.read_body do |chunk|
            io.write chunk
          end
        end
      end
    end

  end
```

**Comment by bryanjbelanger** [comment]
Ok, will take a look at this tonight.

**Comment by bryanjbelanger** [comment]
Need to look at removing open-uri to get this to work.

**Comment by bryanjbelanger** [comment]
kahoffman I have made the changes and done a simple test.

Can you confirm if this works for you?

**Comment by kahoffman** [comment]
I'll give it a try before the end of the week and let you know. Thanks!

**Comment by kahoffman** [comment]
The updates have fixed the problem. Thank you!
