### ISSUE TITLE
No SSL Support

### ISSUE THREAD

**Issue by kahoffman** [autostructure/artifactory_utils#2]
The current module does not support ssl. We have moved our Artifactory instance to ssl to protect user credentials being used. This has broken our use of this module. I've added code to the existing module to fix the problem. Right now, rather than handle SSL certs I turned off SSL verify. This would be the minimum requirement for ssl support. If cert handling is added it would probably be desirable to have a configurable option ssl_verfy you can set to true of false. The change I've added to the existing code is to update the couple of call in the code similar to this:

`Net::HTTP.start(uri.host, uri.port) do |http|`

To this:

`Net::HTTP.start(uri.host, uri.port, :use_ssl => (uri.scheme == 'https'), :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|`

**Comment by bryanjbelanger** [comment]
HI kahoffman,

Thanks for your suggestion. I have added your code verbatim.

I don't have time to thoroughly test right now. If you could see if this works on your existing stuff I would appreciate it greatly.

I will try to get a test added to Travis later tonight.

**Comment by kahoffman** [comment]
I finally downloaded and tested your code. Right now it is not working. You changed for SSL in write_file but not in get_header. You need to make the same update in get_header. i.e.

`http = Net::HTTP.start(uri_get.host, uri_get.port, use_ssl: (uri_get.scheme == 'https'), verify_mode: OpenSSL::SSL::VERIFY_NONE )`

Thanks!

**Comment by bryanjbelanger** [comment]
Added kahoffman changes. Fix works.
