### ISSUE TITLE
Unclear Error Messages On Failed HTTP Other Than 404

### ISSUE THREAD

**Issue by kahoffman** [autostructure/artifactory_utils#3]
You may or may not want to add this but I found the generic error message of "No file can be found at..." is not really sufficient. It is misleading when the error occurred for another reason. I would recommend including the error code in the error messages, i.e.

`raise Puppet::Error, 'No file can be found at ' + url + " (Response code: " + response.code + ")"`

Better yet, handle the file not found condition 404 specifically and put in a second error code for everything else. Maybe something like:

```
        if response.code == "200"
[...]
        elif response.code == "404"
          raise Puppet::Error, 'No file can be found at ' + url 
        else
          raise Puppet::Error, 'Error retrieving file at ' + url + " (Response code: " + response.code + ")"
        end
```

This came up in the process of debugging why ssl was not working, (Issue #2) but I could see this coming up in other cases as well.

**Comment by bryanjbelanger** [comment]
Thanks for your suggestion. This will make it much more user friendly.
